# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCPLEXVersion <- function() {
    .Call(`_cobrarCPLEX_getCPLEXVersion`)
}

initProb <- function(name, tol_bnd) {
    .Call(`_cobrarCPLEX_initProb`, name, tol_bnd)
}

setObjDirLP <- function(xpobj, dir) {
    .Call(`_cobrarCPLEX_setObjDirLP`, xpobj, dir)
}

addColsLP <- function(xpenv, xpx, ncols) {
    .Call(`_cobrarCPLEX_addColsLP`, xpenv, xpx, ncols)
}

addRowsLP <- function(xpenv, xpc, nrows) {
    .Call(`_cobrarCPLEX_addRowsLP`, xpenv, xpc, nrows)
}

loadMatrixLP <- function(xpx, xpc, ne, ia, ja, ra) {
    .Call(`_cobrarCPLEX_loadMatrixLP`, xpx, xpc, ne, ia, ja, ra)
}

setColsBndsObjCoefsLP <- function(xpobj, xpx, indices, lb, ub, objCoefs) {
    .Call(`_cobrarCPLEX_setColsBndsObjCoefsLP`, xpobj, xpx, indices, lb, ub, objCoefs)
}

setRowsBndsLP <- function(xpc, indices, lb, ub) {
    .Call(`_cobrarCPLEX_setRowsBndsLP`, xpc, indices, lb, ub)
}

solveCPLEX <- function(xp, xpmod, xpx, xpc, xpobj) {
    .Call(`_cobrarCPLEX_solveCPLEX`, xp, xpmod, xpx, xpc, xpobj)
}

getSolStatLP <- function(xp) {
    .Call(`_cobrarCPLEX_getSolStatLP`, xp)
}

getObjVal <- function(xp) {
    .Call(`_cobrarCPLEX_getObjVal`, xp)
}

getColsPrimalLP <- function(xp, xpenv, xpx) {
    .Call(`_cobrarCPLEX_getColsPrimalLP`, xp, xpenv, xpx)
}

getColsDualLP <- function(xp, xpenv, xpx) {
    .Call(`_cobrarCPLEX_getColsDualLP`, xp, xpenv, xpx)
}

getNumRowsLP <- function(xpc) {
    .Call(`_cobrarCPLEX_getNumRowsLP`, xpc)
}

setMatRowLP <- function(xpx, xpc, i, len, ind, val) {
    .Call(`_cobrarCPLEX_setMatRowLP`, xpx, xpc, i, len, ind, val)
}

fvaLP <- function(xp, xpmod, xpx, xpc, xpobj, ind) {
    .Call(`_cobrarCPLEX_fvaLP`, xp, xpmod, xpx, xpc, xpobj, ind)
}

