# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCPLEXVersion <- function() {
    .Call(`_cobrarCPLEX_getCPLEXVersion`)
}

initProb <- function(name) {
    .Call(`_cobrarCPLEX_initProb`, name)
}

setObjDirLP <- function(xp, dir) {
    .Call(`_cobrarCPLEX_setObjDirLP`, xp, dir)
}

addColsLP <- function(xp, ncols) {
    .Call(`_cobrarCPLEX_addColsLP`, xp, ncols)
}

addRowsLP <- function(xp, nrows) {
    .Call(`_cobrarCPLEX_addRowsLP`, xp, nrows)
}

loadMatrixLP <- function(xp, ne, ia, ja, ra) {
    .Call(`_cobrarCPLEX_loadMatrixLP`, xp, ne, ia, ja, ra)
}

