# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCPLEXVersion <- function() {
    .Call(`_cobrarCPLEX_getCPLEXVersion`)
}

initProb <- function(name) {
    .Call(`_cobrarCPLEX_initProb`, name)
}

setObjDirLP <- function(xpobj, dir) {
    .Call(`_cobrarCPLEX_setObjDirLP`, xpobj, dir)
}

addColsLP <- function(xpenv, xpx, ncols) {
    .Call(`_cobrarCPLEX_addColsLP`, xpenv, xpx, ncols)
}

addRowsLP <- function(xpenv, xpc, nrows) {
    .Call(`_cobrarCPLEX_addRowsLP`, xpenv, xpc, nrows)
}

loadMatrixLP <- function(xpx, xpc, ne, ia, ja, ra) {
    .Call(`_cobrarCPLEX_loadMatrixLP`, xpx, xpc, ne, ia, ja, ra)
}

setColsBndsObjCoefsLP <- function(xpobj, xpx, indices, lb, ub, objCoefs) {
    .Call(`_cobrarCPLEX_setColsBndsObjCoefsLP`, xpobj, xpx, indices, lb, ub, objCoefs)
}

setRowsBndsLP <- function(xpc, indices, lb, ub) {
    .Call(`_cobrarCPLEX_setRowsBndsLP`, xpc, indices, lb, ub)
}

solveCPLEX <- function(xp, xpenv, xpmod, xpx, xpc, xpobj) {
    .Call(`_cobrarCPLEX_solveCPLEX`, xp, xpenv, xpmod, xpx, xpc, xpobj)
}

